/**
 * * This file is part of the Java Programming Lecture project.
 * *
 * * This file demonstrates the use of a single-dimensional 
 * * array in Java.
 * * A single-dimensional array is a linear data structure that
 * * stores elements of the same type in a contiguous memory location.
 * *
 * * In this example, we create a single-dimensional array of integers,
 * * take input from the user, and print the elements of the array.
 * * 
 * @package I_Unit
 * @author Dr. S. Sampath Kumar
 * @since 10-06-2026
 * @version 2.0
 */

package Java_Array;

import java.util.Scanner;

public class A_Single {

    public static void main(String[] args) {
        // creating object of Scanner class
        Scanner scan = new Scanner(System.in);

        System.out.println("Enter the length of Array: ");
        int arrLength = scan.nextInt();

        int[] anArray;
        // this will give compile time error because array is not initialized
        // System.out.println("Array object before initialization: " + anArray);

        anArray = new int[arrLength];

        System.out.println("Elements of array before assigning values:");
        for (int i : anArray) {
            System.out.print(i + " ");
        }

        System.out.println("\nArray object before initialization: " + anArray);
        System.out.println("Enter the elements of the Array");
        for (int i = 0; i < arrLength; i++) {
            // taking array input
            anArray[i] = scan.nextInt();
        }
        // pint arrays Object
        System.out.println("Array object: " + anArray);

        // toString method of array class will not print the elements of array,
        // it will print the class name and hash code of array object
        // System.out.println(anArray.toString());

        // print class name of array
        // System.out.println(anArray.getClass());

        // print hash code of array object
        System.out.println(anArray.hashCode());

        // what is hash code of array object?
        // The hash code of an array object is a unique identifier that is generated by
        // the
        // Java runtime.
        // It is used to identify the array object in memory and is typically based on
        // the memory address of the array.
        // The hash code is an integer value that can be used for various purposes, such
        // as
        // hashing algorithms, data structures like hash tables, and for debugging
        // purposes.
        // The hash code of an array object is not related to the contents of the array,
        // but rather to the identity of the array object itself. Therefore, two
        // different
        // array objects with the same contents will have different hash codes,
        // while two references to the same array object
        // will have the same hash code.

        // print elements of array
        System.out.println(anArray.length); // this will print the class name and hash code of array object
        System.out.println("Elements of One dimensional array are:");
        for (int i : anArray) {
            System.out.print(i + " ");
        }

    }
}
